apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ankitakalgut/Argo.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: myappdemo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
      
